#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: remove-workflow

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Delete releases and workflows runs
      uses: ophub/delete-releases-workflows@main
      with:
        del_releases: false
        del_workflows: true
        workflows_keep_day: 0
        gh_token: ${{ secrets.GH_TOKEN }}
       
